#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check availability :
if [ cpufreq-set ]
then
	echo ""
else
	echo -e "${RED} [ERROR] cpupowe not found. Try installing... ${NC} \n"
	echo "`sudo apt install cpupower`"
fi

# Count CPUs :
MAX_CPU=$((`nproc --all` - 1))
CPU_FOUND=$((MAX_CPU + 1))
echo -e "${YELLOW} [INFO] Found ${CPU_FOUND} CPUs.\n" 
MIN="400Mhz"
MAX="550Mhz"


# Check params :
if [ $# -eq 2 ]
then
	MIN="$1Mhz"
	MAX="$2Mhz"

		echo -e "${GREEN} [cpupower]: set $MIN ${NC}";
		sudo cpupower frequency-set -d $MIN;
    echo -e "${GREEN} [cpupower]: set $MAX ${NC}";
		sudo cpupower frequency-set -u $MAX;

	# Show new CPU frequencies :
	# cpufreq-info
else
	echo ""
	echo -e "${RED}[NOTE]: It require min & max frequencies (in Mhz):"
	echo ""
	echo -e "	${GREEN} cpupower-set-range 400 800 ${NC}"
	echo ""
fi
